<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>Title</title>
    <link rel="stylesheet" href="css/w3.css">
    <link rel="stylesheet" href="css/main.css">
</head>

<body>
<header class="w3-container w3-blue" style="height: 200px"></header>

<nav class="w3-center w3-black">
    <?php if (!isset($_SESSION['validate'])) :?>
    <a href="/" class="w3-bar-item w3-button">Startseite</a>
    <a href="login" class="w3-bar-item w3-button">Login</a>
    <?php else:?>
    <a href="/" class="w3-bar-item w3-button">Startseite</a>
    <a href="eintrag" class="w3-bar-item w3-button">Eintrag hinzufügen</a>
    <a href="logout" class="w3-bar-item w3-button">Logout</a>
    <?php endif;?>
</nav>
<main>
    <?= $templateOutput ?>
</main>

<footer class="w3-center w3-black">
    <article><label>&copy; 2018 -</label><a href="impressum" class="w3-bar-item  w3-button">Impressum</a></article>
</footer>

</body>
</html>