<form method="post" class="w3-container">
    <p>
        <label>Login</label>
        <input name="login" class="w3-input" type="text"/>
    </p>
    <p>
        <label>Password</label>
        <input type="password" name="password" class="w3-input" />
    </p>
    <p>
        <input type="submit" name="checkingLogin" value="Sign in" class="w3-btn w3-black"/>
    </p>
</form>
<?php if(!empty($errorMessage)) : ?>
    <div class="error"><?= $errorMessage?></div>
<?php endif; ?>
